version: '3'
services:
#  jenkins:
#    image: istresearch/jenkins:latest
#    container_name: jenkins
#    user: jenkins
#    volumes:
#      - /data/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      JENKINS_HOST_HOME: "/data/jenkins"
#    ports:
#      - "8080:8080"


 selenium-hub:
  image: selenium/hub
  ports:
  - 32772:4444

 chrome:
  image: selenium/node-chrome-debug
  ports:
  - 4577 
  links:
  - selenium-hub:hub

 firefox:
  image: selenium/node-firefox-debug
  ports:
  - 4578 
  links:
    - selenium-hub:hub
